### ISSUE TITLE
Incorrect `scm` formatting when there is an empty line in a named node

### ISSUE THREAD

**Issue by pokey** [AndreasArvidsson/andreas-talon-vscode#4]
```scm
(aaa
  (bbb
    (ccc)
  
)
)
```

I also question whether we want to allow an empty line before a `)`. It's common for autoformatters to disallow empty lines at the end of a function body, so seems similar.  I was kind of expecting that empty line to disappear

**Comment by AndreasArvidsson** [comment]
Fixed in latest release
