### ISSUE TITLE
Respect labelFormat setting

### ISSUE THREAD

**Issue by SimeonC** [AndreasArvidsson/andreas-talon-vscode#5]
First of all, thanks for releasing this publicly! Just the tabs view alone is super useful for the one thing I kept resorting to the mouse without fail when using Cursorless.

Would it be possible to respect the "Label Format" setting to make multiple tabs with the same file name easier to switch between? (Or something similar as doing exactly the same may be a bit difficult)

### VSCode Setting
SO answer with pictures of how this works in default tabs; https://stackoverflow.com/a/50181247/1413689

![CleanShot 2023-09-21 at 12 16 08](https://github.com/AndreasArvidsson/andreas-talon-vscode/assets/1085899/cb1095a9-dd7c-4d41-a2e3-198643341d06)

### Current Problem

![CleanShot 2023-09-21 at 12 16 13](https://github.com/AndreasArvidsson/andreas-talon-vscode/assets/1085899/42edfe45-489c-4e4f-8fc7-1f97afcf5487)

### Hackaround

I've hacked a solution by putting the following snippet in [`createItem`](https://github.com/AndreasArvidsson/andreas-talon-vscode/blob/07d777163b157a9a2e3f435b93cad32fa01d60d7/src/tabView.ts#L108) but it's not "great" as I couldn't figure out how to get the whole tree to figure out any duplicates.

```js
const resourceUri = tab.input instanceof vscode.TabInputText ? tab.input.uri : undefined;
const relativePath = vscode.workspace.asRelativePath(resourceUri);
const labelParts = [hint.padStart(2), " - ", relativePath || tab.label];
```

![CleanShot 2023-09-21 at 12 48 07](https://github.com/AndreasArvidsson/andreas-talon-vscode/assets/1085899/59907c32-a357-4738-b513-d5869bc8f8c4)

**Comment by AndreasArvidsson** [comment]
Good idea!

Implemented in version `3.36.0`

**Comment by SimeonC** [comment]
Nice, thanks. That looks much tidier than my hack and I didn't get time to get used to my hack either 😀 
![CleanShot 2023-09-21 at 18 31 54](https://github.com/AndreasArvidsson/andreas-talon-vscode/assets/1085899/c7ecbbf3-b11c-474a-bd66-a333f25d7201)

**Comment by AndreasArvidsson** [comment]
Glad to help. We now also support all of the different label formats in the setting.
