### ISSUE TITLE
can't hover / go to definition for files/folders in .gitignore

### ISSUE THREAD

**Issue by saidelike** [AndreasArvidsson/andreas-talon-vscode#7]
not sure if this is on purpose or not but the hover / go to definition does not work if the `.talon-list` file is in the `.gitignore`.

My use case is having private `settings` with my own `.talon-list` files. They are *not* known by git to avoid sharing them publicly but they are listed in vscode and I find them searching for them but the andreas-talon-vscode extension does not find them for hover / go to definition.

**Comment by AndreasArvidsson** [comment]
That is on purpose

**Comment by saidelike** [comment]
OK then closing thank you
